### ISSUE TITLE
Assert in unit test

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework3G5#18]
Can you guys explain briefly why assert should be used in unit tests and its advantages?

**Comment by reshnashrestha** [comment]
Assertions are used in unit tests to verify that the code under test is behaving as expected. They are a powerful tool for catching bugs early in the development process, and they can help to make your code more reliable and robust.

Here are some of the advantages of using assertions in unit tests:

They make your tests more complete and informative. Assertions tell you exactly what your tests are checking, and they provide detailed error messages if the tests fail. This makes it easier to identify and fix bugs.
They help you to catch bugs early in the development process. Assertions are typically run every time you build your code, so they can catch bugs before they have a chance to propagate through your codebase. This saves you time and effort in the long run.
They help you to document your code. Assertions can be used to document the expected behavior of your code. This can be helpful for other developers who are trying to understand your code or who are working on fixing bugs.
