### ISSUE TITLE
Code line confusion

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G5#40]
Hi group 5,
 It's great that you used projectile motion with air resistance as your function to implement. While I go through your code I am not clear on these lines 
vx=vx-const*dt*vx*math.sqrt((vx**2)+(vy**2)) 
    vy=vy-dt*(g+const*vy*math.sqrt((vx**2)+(vy**2))) 
Also you have used constant value defined earlier in your code. Please help me to understand these lines.

**Comment by reshnashrestha** [comment]
@pratibha77118 This part of the code updates the velocities considering two forces: gravitational acceleration and air drag. The gravitational force acts downward, which is why we subtract g from the vertical velocity vy. The air drag acts against the direction of motion and is dependent on the projectile's speed, hence the use of sqrt((vx**2)+(vy**2)) which calculates the resultant speed. The const value represents the drag coefficient.

I am sorry. I am still working on documentation. I believe that our documentation will clear all these kinds of confusions.
